Vagrant.configure("2") do |config|
  config.vm.box = "<%= node[:vm][:box]%>"
  config.vm.box_url = "<%= node[:vm][:box_url]%>"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network "private_network", ip: "<%= node[:vm][:private_network]%>"
end
